config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  get '/lottery/meet', to: 'lottery#meet'
  get '/lottery/fish', to: 'lottery#fish'
  get '/lottery/vegetable', to: 'lottery#vegetable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rakuten_recipe.rb
# == Schema Information
#
# Table name: rakuten_recipes
#
#  id                :integer          not null, primary key
#  recipeId          :integer
#  recipeTitle       :string
#  recipeUrl         :string
#  foodImageUrl      :string
#  mediumImageUrl    :string
#  smallImageUrl     :string
#  pickup            :integer
#  shop              :integer
#  nickname          :string
#  recipeDescription :string
#  recipeMaterial    :string
#  recipeIndication  :string
#  recipeCost        :string
#  rank              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class RakutenRecipe < ApplicationRecord

  enum category: { invalid_param: 0, meet: 1, fish: 2, vegetable: 3 }

  def self.random_label
    labels = ["handmade", "chance", "latest", "quality"]
    label = labels.sample
    label += ".png"
  end

  def self.get_data(category)
    RakutenRecipe.where(category: category)
  end

  def self.build_from_api(json)

    new(json.extract!(*column_names))
    # image_urls = json.delete(:image_url)
    # code = json.delete(:code)
    # code[:category_name_l].keep_if{|c| c.is_a?(String) }
    # code[:category_name_l].delete("居酒屋")
    # code[:category_name_l].delete("ダイニングバー・バー・ビアホール")
    # code[:category_name_l].delete("ビストロ")

    # json[:gid] = json.delete(:id)
    # json[:image_url_1] = image_urls[:shop_image1]
    # json[:image_url_2] = image_urls[:shop_image2]
    # json[:areaname_s] = code[:areaname_s]
    # json[:category_name_l] = code[:category_name_l].join(",")
    # new(json.extract!(*column_names))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lottery_controller.rb
class LotteryController < ApplicationController
  def meet
    recipes = RakutenRecipe.get_data(RakutenRecipe.categories[:meet])
    @recipes = recipes.sample(3)
    render :show
  end

  def fish
    recipes = RakutenRecipe.get_data(RakutenRecipe.categories[:fish])
    @recipes = recipes.sample(3)

    render :show
  end

  def vegetable
    recipes = RakutenRecipe.get_data(RakutenRecipe.categories[:vegetable])
    @recipes = recipes.sample(3)

    render :show
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuggestDinner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lottery/show.html.erb
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          
            <%= link_to "肉ガチャ", lottery_meet_path , class: "btn btn-primary" %>　　　　
            <%= link_to "魚ガチャ", lottery_fish_path , class: "btn btn-primary" %>　　　　
            <%= link_to "野菜ガチャ", lottery_vegetable_path , class: "btn btn-primary" %>
        </h3>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover ">


          <% @recipes.each do |recipe| %>
            <tr>
                <td>
                  <%= link_to recipe.recipeTitle , recipe.recipeUrl %>
                </td>
              <!-- </tr> -->
              <!-- <tr> -->
              <td>
              <%= recipe.recipeDescription %>
              </td>
              <!-- </tr> -->
              <!-- <tr> -->
                <td>
                  材料<br>
                  <%= recipe.recipeMaterial %>
                </td>
                <tr>
                <td>
                  <%= image_tag(RakutenRecipe.random_label, alt: "アイコン", size: "192x96") %>
                </td>
                <td colspan=2>
                  <% recipe.rank.to_i.times do %>
                    <%= image_tag("star.png", :alt => "アイコン", :size => "64x64") %>
                  <% end %>
                </td>
                </tr>
              </tr>
              <tr>
                <td>
                  <% if recipe.foodImageUrl? && recipe.foodImageUrl != "{}" %>
                  <%= image_tag recipe.foodImageUrl , :size => '200x200' %>
                  <% end %>
                </td>
            </tr>
          <% end %>

          </tbody>
        </table> 
      </div>
    </div>

app/views/top/index.html.erb
<p id="notice"><%= notice %></p>

<h1>今夜のメシガチャ</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <div class="panel panel-primary">
      <div class="panel-body">
        <table class="table table-striped table-hover ">
          <tbody>
            <%= link_to "肉ガチャ", lottery_meet_path , class: "btn btn-primary" %>
            <br><br>
            <%= link_to "魚ガチャ", lottery_fish_path , class: "btn btn-primary" %>
<br><br>
            <%= link_to "野菜ガチャ", lottery_vegetable_path , class: "btn btn-primary" %>
<br><br>

          </tbody>
        </table> 
      </div>
    </div>


  </tbody>
</table>

<br>